run1_gluoncv:
  backend: gluoncv_backend
  backbone: resnet50
  epochs: 10
  batch_size: 1
  learn_rate: 0.001
  pretrained: True
  width: 480
  height: 480
  orig_width: 580
  orig_height: 420
  summarysteps: 1
  flip: True
  zoom_in: 0.5
  zoom_out: 0.5
  color_img: True
  gray_mask: True
  filters:
   - 'protoseg.filters.sobel.sobel': [1,0,5]
   - 'protoseg.filters.sobel.sobel': [0,1]
  