run1_gluoncv:
  backend: gluoncv_backend
  backbone: resnet50
  epochs: 10
  batch_size: 1
  learn_rate: 0.001
  pretrained: True
  width: 480
  height: 480
  summarysteps: 1
  flip: True
  horizontal_flip: True
  rotation_degree: 30
  horizontal_shift: 20
  vertical_shift: 30
  noise_amount: 20
  noise_chance: 0.5