run1_shipdetection:
  datapath: ~/.kaggle/competitions/airbus-ship-detection/smalldataset
  backend: ptsemseg_backend
  backbone: unet
  classes: 2
  epochs: 10
  batch_size: 1
  learn_rate: 0.001
  pretrained: True
  width: 572
  height: 572
  mask_width: 388
  mask_height: 388
  orig_width: 768
  orig_height: 768
  summarysteps: 2
  flip: True
  zoom_in: 0.5
  zoom_out: 0.5
  gray_img: True
  gray_mask: True
#  filters:
#    - 'cv2.Canny': [100,200]
#    - 'protoseg.filters.canny.addcanny': [100,200]
#   - 'protoseg.filters.sobel.sobel': [1,0,5]
#    - 'protoseg.filters.sobel.sobel': [0,1]
#    - 'protoseg.filters.laplacian.laplacian': []
#    - 'protoseg.filters.laplacian.addlaplacian': []
#    - 'protoseg.filters.morphological.erosion': [5,5,1]
#    - 'protoseg.filters.morphological.dilation': [5,5,2]
#    - 'protoseg.filters.morphological.opening': [5,5,1]
  metrices:
    - 'pixel_accuracy': 'protoseg.metrices.accuracy.pixel_accuracy'
    - 'dice': 'protoseg.metrices.dice.dice'
    - 'iou': 'protoseg.metrices.iou.iou'
  hyperparamopt:
    - flip: [True, False]
    - filters: [['protoseg.filters.canny.addcanny': [100,200]],['protoseg.filters.morphological.opening': [5,5,1]]]